name: Build and Push Docker image to ACR

on:
  push:
    tags:
      - release-v**

jobs:
  ai-model-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Alibaba Cloud Container Registry (ACR) Login
        uses: aliyun/acr-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          region-id: cn-shanghai
          login-server: registry.cn-shanghai.aliyuncs.com

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: get_version
        name: Get version
        run: echo "::set-output name=version::$(echo ${{ github.ref_name }} | sed 's|release-v||g')"

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./ai-model-workspace
          file: ./ai-model-workspace/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mrchengxin/ai-model-workspace:latest
            mrchengxin/ai-model-workspace:${{ steps.get_version.outputs.version }}
            registry.cn-shanghai.aliyuncs.com/mrchengxin/ai-model-workspace:latest
            registry.cn-shanghai.aliyuncs.com/mrchengxin/ai-model-workspace:${{ steps.get_version.outputs.version }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mrchengxin/ai-model-workspace
